import{a as O,S as P,i as c}from"./assets/vendor-c493984e.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();const q="44834874-d7e209ef58742400d75504b10",M="https://pixabay.com/api";async function R(a,n,r){const{data:i}=await O.get(`${M}/?key=${q}&q=${a}&image_type=photo&orientation=horizontal&safesearch=true&per_page=${r}&page=${n}`);return i}document.addEventListener("DOMContentLoaded",C);function C(){const a=document.getElementById("search-form"),n=document.querySelector(".gallery"),r=document.querySelector(".load-more");let i="",t=1;const o=40,s=new P(".gallery a",{captionsData:"alt",captionDelay:250});r.style.display="none",a.addEventListener("submit",f),r.addEventListener("click",u);async function f(e){if(e.preventDefault(),n.innerHTML="",i=e.target.searchQuery.value.trim(),!i){L("Search input must not be empty!"),e.target.searchQuery.value="",r.style.display="none";return}t=1,await u()}async function u(){try{const e=await R(i,t,o);p(e)}catch(e){m(e)}}function p(e){if(e.totalHits===0){r.style.display="none",d("Sorry, there are no images matching your search query.");return}y(e.hits),t===1?w(`Hooray! We found ${e.totalHits} images.`):h(),b(e.totalHits),t+=1}function m(e){console.error(e),d("There was a problem fetching images. Please try again later.")}function y(e){const l=e.map(g).join("");n.insertAdjacentHTML("beforeend",l),s.refresh()}function g({webformatURL:e,largeImageURL:l,tags:$,likes:S,views:E,comments:I,downloads:H}){return`
      <div class="photo-card">
        <a href="${l}">
          <img src="${e}" alt="${$}" loading="lazy" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b> ${S}</p>
          <p class="info-item"><b>Views</b> ${E}</p>
          <p class="info-item"><b>Comments</b> ${I}</p>
          <p class="info-item"><b>Downloads</b> ${H}</p>
        </div>
      </div>
    `}function h(){const{height:e}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}function b(e){t*o>=e?(r.style.display="none",v("Sorry, it looks like you've reached the end of the search results")):r.style.display="block"}function d(e){c.error({title:"Error",position:"topRight",message:e})}function w(e){c.success({title:"Success",position:"topRight",message:e})}function v(e){c.info({title:"Info",position:"topRight",message:e})}function L(e){c.warning({title:"Warning",position:"topRight",message:e})}}
//# sourceMappingURL=commonHelpers.js.map
